### ISSUE TITLE
Support for yaml

### ISSUE THREAD

**Issue by xstar97** [heysupratim/npmsync#1]
Support for yaml will likely be a huge plus; it's a easier and more manageable data structure compared to json.

When I have free time I might make a pr later to add support for it; not entirely replace json though. 

```yaml
- domain_names:
    - subdomain1.domain.com
  forward_host: 192.168.1.64
  forward_port: 9898
  forward_scheme: http
  caching_enabled: false
  block_exploits: false
  allow_websocket_upgrade: true
  ssl_forced: true
  http2_support: true
  hsts_enabled: true
  hsts_subdomains: false
  enabled: true
  meta:
    letsencrypt_agree: true
    dns_challenge: false
  advanced_config: ""
  locations: []
- domain_names:
    - subdomain2.domain.com
  forward_host: 192.168.1.64
  forward_port: 9898
  forward_scheme: http
  caching_enabled: false
  block_exploits: false
  allow_websocket_upgrade: true
  ssl_forced: true
  http2_support: true
  hsts_enabled: true
  hsts_subdomains: false
  enabled: true
  meta:
    letsencrypt_agree: true
    dns_challenge: false
  advanced_config: ""
  locations: []
```
